[tool.versioningit]

[tool.versioningit.format]
distance = "{base_version}-{distance}.{vcs}{rev}"
dirty = "{base_version}-{distance}.{vcs}{rev}.dirty"
distance-dirty = "{base_version}-{distance}.{vcs}{rev}.dirty"
